ad_feature <- read.csv("C:/Users/Student/Desktop/AdClick Data fromTaobao/ad_feature.csv")
user_profile <- read.csv("C:/Users/Student/Desktop/AdClick Data fromTaobao/user_profile.csv")
raw_sample <- read.csv("C:/Users/Student/Desktop/AdClick Data fromTaobao/raw_sample.csv")
library(data.table)
mergeAdUser <- fread("C:/Users/Student/Desktop/AdClick Data fromTaobao/mergeAdUser.csv")
